# Generated by Django 4.1.7 on 2023-03-06 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=30)),
                ('message', models.CharField(default=None, max_length=300)),
                ('date', models.DateField(default=datetime.date(2023, 3, 6))),
            ],
        ),
    ]
