# Generated by Django 4.1.7 on 2023-03-06 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 6, 10, 14, 29, 877511, tzinfo=datetime.timezone.utc)),
        ),
    ]
