# Generated by Django 4.1.7 on 2023-03-06 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0002_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 6, 15, 47, 8, 320359)),
        ),
    ]
