# Generated by Django 4.1.7 on 2023-03-12 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0003_alter_membership_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 20, 14, 6, 949756)),
        ),
    ]
