# Generated by Django 4.1.7 on 2023-03-09 16:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0004_alter_contact_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=30)),
                ('fileContent', models.TextField(default=None)),
                ('fileNumber', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 9)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 9, 21, 46, 50, 339963)),
        ),
    ]
