# Generated by Django 4.1.7 on 2023-03-09 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0005_savefile_alter_contact_date_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
