# Generated by Django 4.1.7 on 2023-03-09 19:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0007_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=30)),
                ('plan_name', models.CharField(default=None, max_length=30)),
                ('total_file_remaining', models.IntegerField(default=0)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=datetime.datetime(2023, 4, 8, 19, 23, 49, 573906, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
