# Generated by Django 4.1.7 on 2023-03-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0008_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savefile',
            old_name='fileNumber',
            new_name='file_number',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.RemoveField(
            model_name='savefile',
            name='fileContent',
        ),
        migrations.AddField(
            model_name='savefile',
            name='file_content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 8, 20, 55, 9, 43467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='username',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
