# Generated by Django 4.1.7 on 2023-03-10 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0011_membership_old_file_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='download_file',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membership',
            name='upload_file',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 5, 36, 4, 9455, tzinfo=datetime.timezone.utc)),
        ),
    ]
