# Generated by Django 4.1.7 on 2023-03-10 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0012_membership_download_file_membership_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 15, 49, 51, 527302, tzinfo=datetime.timezone.utc)),
        ),
    ]
